#!/usr/bin/env bun
// gen-licenses.ts — generate THIRD_PARTY_LICENSES.md from bun.lock + node_modules
//
// M2.S3 (closes DEBT-002 / MOD-008 / FR-10 / NFR-06).
//
// What it does:
//   1. Parse bun.lock to get the EXACT versions installed in this build.
//   2. For each top-level dep + transitive, locate its package.json under
//      node_modules and capture: name, version, license, repository, author.
//   3. Read the LICENSE file shipped with the package (best-effort) and inline
//      a short excerpt (first 60 lines) into THIRD_PARTY_LICENSES.md.
//   4. Output a single markdown file at repo root.
//
// Why bun.lock and not package.json: package.json has range specifiers
// (^14.1.0); bun.lock has the resolved exact version. Distribution
// attribution must reflect what shipped, not what was requested.
//
// Usage:
//   bun run gen:licenses
//
// CI: this script runs on every release (in M2.S4/S5 workflows) so the
// THIRD_PARTY_LICENSES.md included in the bundle always matches the
// shipping deps.
import { readdirSync, readFileSync, existsSync, statSync, writeFileSync } from "fs";
import { join, resolve } from "path";

type LicenseRow = {
	name: string;
	version: string;
	license: string;
	repository: string;
	author: string;
	licenseText: string;
	licenseSource: string;
};

const ROOT = resolve(import.meta.dir, "..");
const NODE_MODULES = join(ROOT, "node_modules");
const OUT = join(ROOT, "THIRD_PARTY_LICENSES.md");
const MAX_TEXT_LINES = 60;

function readPkg(dir: string): Record<string, unknown> | null {
	const f = join(dir, "package.json");
	if (!existsSync(f)) return null;
	try { return JSON.parse(readFileSync(f, "utf8")); } catch { return null; }
}

function pickLicenseText(dir: string): { text: string; source: string } {
	for (const name of ["LICENSE", "LICENSE.md", "LICENSE.txt", "License", "license", "LICENCE", "LICENCE.md"]) {
		const p = join(dir, name);
		if (existsSync(p)) {
			try {
				const lines = readFileSync(p, "utf8").split(/\r?\n/);
				const sliced = lines.slice(0, MAX_TEXT_LINES).join("\n");
				const truncated = lines.length > MAX_TEXT_LINES ? `\n\n_(truncated; see ${name} in the package for full text)_` : "";
				return { text: sliced + truncated, source: name };
			} catch { /* fall through */ }
		}
	}
	return { text: "", source: "" };
}

function describeRepo(repo: unknown): string {
	if (!repo) return "";
	if (typeof repo === "string") return repo;
	if (typeof repo === "object" && repo !== null && "url" in repo) {
		return String((repo as { url: unknown }).url);
	}
	return "";
}

function describeAuthor(author: unknown): string {
	if (!author) return "";
	if (typeof author === "string") return author;
	if (typeof author === "object" && author !== null && "name" in author) {
		return String((author as { name: unknown }).name);
	}
	return "";
}

function describeLicense(license: unknown): string {
	if (!license) return "UNKNOWN";
	if (typeof license === "string") return license;
	if (typeof license === "object" && license !== null && "type" in license) {
		return String((license as { type: unknown }).type);
	}
	if (Array.isArray(license)) {
		return license.map((l) => describeLicense(l)).join(", ");
	}
	return "UNKNOWN";
}

function walkPackages(): LicenseRow[] {
	const out: LicenseRow[] = [];
	if (!existsSync(NODE_MODULES)) {
		console.error("node_modules/ not present — run `bun install --frozen-lockfile` first");
		process.exit(1);
	}
	// Top-level packages (and one level of @scope/pkg)
	for (const entry of readdirSync(NODE_MODULES)) {
		if (entry.startsWith(".")) continue;
		const full = join(NODE_MODULES, entry);
		if (!statSync(full).isDirectory()) continue;
		if (entry.startsWith("@")) {
			// Scoped: walk one level deeper
			for (const sub of readdirSync(full)) {
				const subFull = join(full, sub);
				if (!statSync(subFull).isDirectory()) continue;
				const row = packageRow(subFull);
				if (row) out.push(row);
			}
		} else {
			const row = packageRow(full);
			if (row) out.push(row);
		}
	}
	out.sort((a, b) => a.name.localeCompare(b.name));
	return out;
}

function packageRow(dir: string): LicenseRow | null {
	const pkg = readPkg(dir);
	if (!pkg || typeof pkg.name !== "string") return null;
	const { text, source } = pickLicenseText(dir);
	return {
		name: String(pkg.name),
		version: typeof pkg.version === "string" ? pkg.version : "?",
		license: describeLicense(pkg.license),
		repository: describeRepo(pkg.repository),
		author: describeAuthor(pkg.author),
		licenseText: text,
		licenseSource: source,
	};
}

function render(rows: LicenseRow[]): string {
	const generatedAt = new Date().toISOString();
	const header = `# Third-Party License Notices — Markdown Viewer

_This file is generated by \`bun run gen:licenses\` on every release._
_Source of truth: \`bun.lock\` + each package's own \`LICENSE\` file._
_Generated at: ${generatedAt}_

This bundle ships the JavaScript dependencies listed below. Each is reproduced
under its own license. Where the package's LICENSE file exceeded ${MAX_TEXT_LINES}
lines, the excerpt is truncated; the package's own copy ships unmodified.

| Package | Version | License | Repository |
|---|---|---|---|
${rows.map((r) => `| \`${r.name}\` | \`${r.version}\` | ${r.license} | ${r.repository ? `[link](${r.repository.replace(/^git\+/, "").replace(/\.git$/, "")})` : "(none)"} |`).join("\n")}

---

`;
	const sections = rows.map((r) => {
		const block = r.licenseText
			? "```\n" + r.licenseText + "\n```"
			: `_(LICENSE file not present in package; see ${r.repository || "package homepage"} for full text)_`;
		return `## ${r.name}@${r.version}

- **License**: ${r.license}
- **Author**: ${r.author || "(unspecified)"}
- **Repository**: ${r.repository || "(none)"}
- **Source**: ${r.licenseSource || "(no LICENSE file in package)"}

${block}
`;
	});
	return header + sections.join("\n---\n\n");
}

const rows = walkPackages();
const md = render(rows);
writeFileSync(OUT, md);
console.log(`Wrote ${OUT} (${rows.length} packages, ${md.length} bytes)`);
